
project_id = "uheksobnyedarrpgxhju"

[api]
enabled = true
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://uheksobnyedarrpgxhju.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.places-visibility-check]
verify_jwt = false

[functions.webhooks-meta]
verify_jwt = false

[functions.enhanced-contact-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true

[functions.sync-gmb]
verify_jwt = true

[functions.sync-ga4]
verify_jwt = true

[functions.fetch-kpi]
verify_jwt = true

[functions.google-job-worker]
verify_jwt = true

[functions.activate-billing]
verify_jwt = true

[functions.token-refresh]
verify_jwt = true

[functions.alert-dismiss]
verify_jwt = true

[functions.send-visibility-report]
verify_jwt = false

[functions.generate-pdf-report]
verify_jwt = false

[functions.log_uploader]
verify_jwt = false

[functions.bedrock-integration]
verify_jwt = false

[functions.ai-category-tagging]
verify_jwt = false
