project_id = "uheksobnyedarrpgxhju"

[functions.enhanced-visibility-check]
verify_jwt = false

[functions.bedrock-analysis]
verify_jwt = false

[functions.vc-start-analysis]
verify_jwt = false

[functions.vc-confirm-email]
verify_jwt = false

[functions.vc-result]
verify_jwt = false

[functions.vc-dev-complete]
verify_jwt = false
