/**
 * TASK 6.3.1e - Claude Recommendation Generation für goalId = group_bookings
 * 
 * Ziel: Für das Geschäftsziel "group_bookings" (Gruppenbuchungen erhöhen) 
 * werden 5 konkrete Empfehlungen generiert für Buchungen von Gruppen, Familien & B2B-Terminen.
 * 
 * Generated by: Claude AI via Bedrock
 * Target: Lokale Restaurants, Cafés, Bars mit digital-affiner Kundschaft
 * Personas: Anna (Gen Z/Yoga/Instagram/Bio), Markus (Familienvater/organisiert/Google/lokal)
 */

import { GoalRecommendation } from '../../types/goal-recommendations';

export const group_bookings_recommendations: GoalRecommendation[] = [
  {
    goalId: "group_bookings",
    recommendationId: "group_dedicated_booking_page",
    title: "Spezielle Gruppenbuchungs-Landingpage erstellen",
    description: "Entwickle eine dedizierte Webseite für Gruppenbuchungen mit klaren Paketangeboten, Raumfotos und einem einfachen Anfrage-Formular. Zeige verschiedene Gruppengrößen (8-12, 15-20, 25+ Personen) mit entsprechenden Menüoptionen und Preisen. Dies professionalisiert den Buchungsprozess und reduziert Anfrage-Aufwand erheblich.",
    platform: "Website",
    impactScore: 9,
    effortScore: 6,
    personaTargets: ["Wachstums-Walter", "Ketten-Katrin"]
  },
  {
    goalId: "group_bookings",
    recommendationId: "group_corporate_lunch_packages",
    title: "Business-Lunch-Pakete für Firmen entwickeln",
    description: "Erstelle spezielle Menüpakete für Geschäftsessen mit verschiedenen Preisstufen (Basic, Premium, Executive). Biete Services wie Präsentationstechnik, separate Räume oder Catering-Optionen an. Kontaktiere lokale Unternehmen direkt und biete Probe-Termine an. Dies erschließt den lukrativen B2B-Markt mit planbaren, wiederkehrenden Buchungen.",
    platform: "Offline",
    impactScore: 10,
    effortScore: 8,
    personaTargets: ["Ketten-Katrin", "Wachstums-Walter"]
  },
  {
    goalId: "group_bookings",
    recommendationId: "group_family_celebration_promotion",
    title: "Familienfeiern-Pakete aktiv bewerben",
    description: "Entwickle attraktive Pakete für Geburtstage, Taufen oder Familienfeiern mit Kindermenüs, Dekoration und flexiblen Zeitfenstern. Bewirb diese über Facebook (Familiengruppen) und Google Ads mit Keywords wie 'Kindergeburtstag Restaurant [Stadt]'. Biete Planungshilfen und Checklisten an, um Eltern die Organisation zu erleichtern.",
    platform: "Facebook",
    impactScore: 8,
    effortScore: 5,
    personaTargets: ["Bewahrer-Ben", "Solo-Sarah"]
  },
  {
    goalId: "group_bookings",
    recommendationId: "group_instagram_event_showcase",
    title: "Erfolgreiche Gruppenfeiern auf Instagram zeigen",
    description: "Dokumentiere (mit Erlaubnis) gelungene Gruppenfeiern und teile diese als Posts und Stories. Zeige die Atmosphäre, das Essen und zufriedene Gäste. Nutze Hashtags wie #Firmenfeier #Geburtstag #Gruppenessen. Diese authentischen Einblicke inspirieren andere zur Buchung und zeigen deine Event-Kompetenz.",
    platform: "Instagram",
    impactScore: 7,
    effortScore: 3,
    personaTargets: ["Wachstums-Walter"]
  },
  {
    goalId: "group_bookings",
    recommendationId: "group_referral_incentive_program",
    title: "Empfehlungsprogramm für Gruppenbuchungen einführen",
    description: "Biete bestehenden Kunden Anreize für erfolgreiche Gruppenempfehlungen (z.B. 10% Rabatt auf nächste Buchung oder Gratis-Vorspeise). Erstelle Empfehlungskarten zum Weitergeben und tracke Empfehlungen digital. Mundpropaganda ist bei Gruppenbuchungen besonders effektiv, da Vertrauen und persönliche Erfahrungen entscheidend sind.",
    platform: "Offline",
    impactScore: 8,
    effortScore: 4,
    personaTargets: ["Bewahrer-Ben", "Ketten-Katrin"]
  }
];

export default group_bookings_recommendations;