/**
 * TASK 6.3.1d - Claude Recommendation Generation für goalId = ig_growth
 * 
 * Ziel: Für das Geschäftsziel "ig_growth" (Instagram-Wachstum) 
 * werden 5 konkrete Empfehlungen generiert für Reels, Stories, Posts & visuelle Konsistenz zur organischen Reichweite.
 * 
 * Generated by: Claude AI via Bedrock
 * Target: Lokale Restaurants, Cafés, Bars mit digital-affiner Kundschaft
 * Personas: Anna (Gen Z/Yoga/Instagram/Bio), Markus (Familienvater/organisiert/Google/lokal)
 */

import { GoalRecommendation } from '../../types/goal-recommendations';

export const ig_growth_recommendations: GoalRecommendation[] = [
  {
    goalId: "ig_growth",
    recommendationId: "ig_daily_food_reels",
    title: "Tägliche Food-Preparation Reels erstellen",
    description: "Filme täglich 15-30 Sekunden der Speisenzubereitung als Reels mit trendiger Musik. Zeige das Anrichten, Flammen beim Flambieren oder das Aufschäumen von Milch. Diese authentischen Behind-the-Scenes-Momente generieren hohe Engagement-Raten und werden vom Instagram-Algorithmus bevorzugt. Nutze relevante Food-Hashtags für maximale Reichweite.",
    platform: "Instagram",
    impactScore: 9,
    effortScore: 4,
    personaTargets: ["Wachstums-Walter"]
  },
  {
    goalId: "ig_growth",
    recommendationId: "ig_consistent_visual_branding",
    title: "Einheitliches visuelles Branding entwickeln",
    description: "Erstelle ein konsistentes Farbschema, Filter-Preset und Layout für alle Posts. Nutze wiederkehrende Elemente wie dein Logo-Wasserzeichen oder charakteristische Teller/Hintergründe. Diese visuelle Konsistenz macht dein Restaurant sofort erkennbar im Feed und wirkt professionell. Erstelle Templates für Stories und Posts.",
    platform: "Instagram",
    impactScore: 8,
    effortScore: 6,
    personaTargets: ["Wachstums-Walter", "Ketten-Katrin"]
  },
  {
    goalId: "ig_growth",
    recommendationId: "ig_user_generated_content",
    title: "User-Generated Content aktiv fördern",
    description: "Ermutige Gäste, Fotos zu teilen, indem du einen einprägsamen Hashtag (#MeinMomentBei[RestaurantName]) erstellst und bewirbst. Reposte die besten Gäste-Fotos in deinen Stories mit Verlinkung. Biete kleine Belohnungen für getaggte Posts an. Dies schafft authentischen Content und erhöht deine Reichweite durch die Netzwerke deiner Gäste.",
    platform: "Instagram",
    impactScore: 8,
    effortScore: 3,
    personaTargets: ["Wachstums-Walter"]
  },
  {
    goalId: "ig_growth",
    recommendationId: "ig_trending_hashtag_strategy",
    title: "Strategische Hashtag-Mischung mit Trending-Tags",
    description: "Kombiniere 5-10 nischige Restaurant-Hashtags (#[Stadt]Foodie) mit 10-15 populären Food-Hashtags (#Foodstagram) und 5 Trending-Hashtags. Recherchiere wöchentlich neue Trending-Tags in deiner Region. Diese Mischung maximiert sowohl die Auffindbarkeit in deiner Nische als auch die Reichweite durch populäre Tags.",
    platform: "Instagram",
    impactScore: 7,
    effortScore: 4,
    personaTargets: ["Wachstums-Walter"]
  },
  {
    goalId: "ig_growth",
    recommendationId: "ig_interactive_stories_polls",
    title: "Interaktive Stories mit Umfragen und Fragen",
    description: "Nutze täglich Instagram Story-Features wie Umfragen ('Pizza oder Pasta heute?'), Frage-Sticker ('Was ist euer Lieblingsgericht?') oder Quiz-Sticker über euer Menü. Diese Interaktionen steigern das Engagement erheblich und signalisieren dem Algorithmus hohe Nutzer-Aktivität. Antworte persönlich auf Fragen, um Community-Gefühl zu schaffen.",
    platform: "Instagram",
    impactScore: 8,
    effortScore: 2,
    personaTargets: ["Wachstums-Walter"]
  }
];

export default ig_growth_recommendations;