/**
 * TASK 6.3.1a - Claude Recommendation Generation für goalId = increase_reviews
 * 
 * Ziel: Für das Geschäftsziel "increase_reviews" (mehr Google-Bewertungen erhalten) 
 * werden 5 konkrete Empfehlungen generiert, die auf die Zielgruppe zugeschnitten sind.
 * 
 * Generated by: Claude AI via Bedrock
 * Target: Lokale Restaurants, Cafés, Bars mit digital-affiner Kundschaft
 * Personas: Anna (Gen Z/Yoga/Instagram/Bio), Markus (Familienvater/organisiert/Google/lokal)
 */

import { GoalRecommendation } from '../../types/goal-recommendations';

export const increase_reviews_recommendations: GoalRecommendation[] = [
  {
    goalId: "increase_reviews",
    recommendationId: "rev_email_reminder",
    title: "Erinnere Gäste per E-Mail an eine Bewertung",
    description: "Nutze automatisierte E-Mail-Erinnerungen 24-48 Stunden nach einem Besuch, um Gäste freundlich an eine Google-Bewertung zu erinnern. Dies erhöht signifikant die Antwortrate um bis zu 300% und stärkt die Kundenbindung. Personalisiere die E-Mail mit dem Namen des Gastes und erwähne spezielle Gerichte oder Momente des Besuchs.",
    platform: "Google",
    impactScore: 9,
    effortScore: 4,
    personaTargets: ["Bewahrer-Ben", "Solo-Sarah"]
  },
  {
    goalId: "increase_reviews",
    recommendationId: "rev_qr_table_cards",
    title: "QR-Code Tischkarten für sofortige Bewertungen",
    description: "Platziere ansprechende Tischkarten mit QR-Codes, die direkt zur Google-Bewertungsseite führen. Gäste können während oder direkt nach dem Essen bewerten, wenn die Erfahrung noch frisch ist. Kombiniere dies mit einem kleinen Anreiz wie 'Nächster Kaffee gratis bei 5-Sterne-Bewertung'.",
    platform: "Google",
    impactScore: 8,
    effortScore: 2,
    personaTargets: ["Solo-Sarah", "Wachstums-Walter"]
  },
  {
    goalId: "increase_reviews",
    recommendationId: "rev_instagram_story_cta",
    title: "Instagram Stories mit Bewertungs-Call-to-Action",
    description: "Erstelle regelmäßige Instagram Stories, die zufriedene Gäste beim Essen zeigen und mit einem direkten Link zur Google-Bewertung versehen sind. Nutze interaktive Elemente wie Umfragen oder Fragen, um Engagement zu fördern. Dies erreicht besonders digital-affine Zielgruppen effektiv.",
    platform: "Instagram",
    impactScore: 7,
    effortScore: 3,
    personaTargets: ["Wachstums-Walter"]
  },
  {
    goalId: "increase_reviews",
    recommendationId: "rev_staff_training_moments",
    title: "Mitarbeiter-Training für Bewertungsmomente",
    description: "Schule dein Team, natürliche Momente zu erkennen, in denen Gäste besonders zufrieden sind (nach dem Hauptgang, beim Dessert) und höflich nach einer Bewertung zu fragen. Ein authentisches 'Hat Ihnen alles geschmeckt? Eine kurze Google-Bewertung würde uns sehr helfen' wirkt Wunder. Biete dem Team kleine Belohnungen für erfolgreiche Bewertungsanfragen.",
    platform: "Offline",
    impactScore: 8,
    effortScore: 5,
    personaTargets: ["Bewahrer-Ben", "Ketten-Katrin"]
  },
  {
    goalId: "increase_reviews",
    recommendationId: "rev_loyalty_program_integration",
    title: "Bewertungen in Treueprogramm integrieren",
    description: "Verknüpfe Google-Bewertungen mit deinem Treueprogramm oder Bonussystem. Gäste erhalten Punkte oder Rabatte für ehrliche Bewertungen. Dies schafft einen kontinuierlichen Anreiz und erhöht sowohl die Bewertungsanzahl als auch die Kundentreue. Kommuniziere dies über Website, Social Media und vor Ort.",
    platform: "Website",
    impactScore: 9,
    effortScore: 6,
    personaTargets: ["Wachstums-Walter", "Ketten-Katrin"]
  }
];

// Export für Integration in das Hauptsystem
export default increase_reviews_recommendations;