/**
 * TASK 6.3.1b - Claude Recommendation Generation für goalId = local_visibility
 * 
 * Ziel: Für das Geschäftsziel "local_visibility" (lokale Sichtbarkeit steigern) 
 * werden 5 konkrete Empfehlungen generiert für verbesserte Auffindbarkeit bei "in der Nähe"-Suchanfragen.
 * 
 * Generated by: Claude AI via Bedrock
 * Target: Lokale Restaurants, Cafés, Bars mit digital-affiner Kundschaft
 * Personas: Anna (Gen Z/Yoga/Instagram/Bio), Markus (Familienvater/organisiert/Google/lokal)
 */

import { GoalRecommendation } from '../../types/goal-recommendations';

export const local_visibility_recommendations: GoalRecommendation[] = [
  {
    goalId: "local_visibility",
    recommendationId: "loc_gmb_optimization",
    title: "Google My Business Profil vollständig optimieren",
    description: "Vervollständige alle Felder deines Google My Business Profils: Öffnungszeiten, Telefonnummer, Website, Kategorien und Attribute. Lade hochwertige Fotos von Gerichten, Innenräumen und dem Team hoch. Ein vollständiges Profil wird bei lokalen Suchanfragen bis zu 70% häufiger angezeigt. Aktualisiere regelmäßig Posts und Angebote.",
    platform: "Google",
    impactScore: 10,
    effortScore: 3,
    personaTargets: ["Bewahrer-Ben", "Solo-Sarah"]
  },
  {
    goalId: "local_visibility",
    recommendationId: "loc_local_keywords_website",
    title: "Lokale Keywords auf Website integrieren",
    description: "Optimiere deine Website mit lokalen Suchbegriffen wie 'Restaurant [Stadtteil]', 'Pizza [Straßenname]' oder 'Café [Bezirk]'. Erstelle eine Standortseite mit Anfahrtsbeschreibung, lokalen Sehenswürdigkeiten und Parkmöglichkeiten. Dies verbessert deine Sichtbarkeit bei 'in der Nähe'-Suchanfragen erheblich.",
    platform: "Website",
    impactScore: 8,
    effortScore: 4,
    personaTargets: ["Wachstums-Walter", "Ketten-Katrin"]
  },
  {
    goalId: "local_visibility",
    recommendationId: "loc_neighborhood_partnerships",
    title: "Partnerschaften mit lokalen Unternehmen aufbauen",
    description: "Kooperiere mit nahegelegenen Geschäften, Fitnessstudios oder Büros für Cross-Promotion. Biete Mitarbeiterrabatte an oder organisiere gemeinsame Events. Diese lokalen Verbindungen stärken deine Präsenz im Viertel und generieren wertvolle lokale Backlinks und Mundpropaganda.",
    platform: "Offline",
    impactScore: 7,
    effortScore: 6,
    personaTargets: ["Bewahrer-Ben", "Wachstums-Walter"]
  },
  {
    goalId: "local_visibility",
    recommendationId: "loc_geotagged_social_posts",
    title: "Geotagging in allen Social Media Posts",
    description: "Verwende konsequent Standort-Tags in Instagram, Facebook und Google Posts. Tagge nicht nur dein Restaurant, sondern auch nahegelegene Landmarks, U-Bahn-Stationen oder beliebte Plätze. Dies erhöht die Wahrscheinlichkeit, dass Nutzer in der Nähe deine Inhalte entdecken und dein Restaurant finden.",
    platform: "Instagram",
    impactScore: 6,
    effortScore: 2,
    personaTargets: ["Wachstums-Walter"]
  },
  {
    goalId: "local_visibility",
    recommendationId: "loc_local_directory_listings",
    title: "Einträge in lokale Verzeichnisse und Apps",
    description: "Registriere dich in lokalen Verzeichnissen wie Yelp, TripAdvisor, Foursquare und stadtspezifischen Apps. Achte auf konsistente NAP-Daten (Name, Adresse, Telefon) überall. Diese Citations stärken deine lokale SEO-Autorität und machen dich für verschiedene Zielgruppen auffindbar.",
    platform: "Website",
    impactScore: 8,
    effortScore: 5,
    personaTargets: ["Ketten-Katrin", "Bewahrer-Ben"]
  }
];

export default local_visibility_recommendations;