/**
 * TASK 6.3.1c - Claude Recommendation Generation für goalId = lunch_conversion
 * 
 * Ziel: Für das Geschäftsziel "lunch_conversion" (Mittagstisch pushen) 
 * werden 5 konkrete Empfehlungen generiert für erhöhte Sichtbarkeit und Relevanz von Mittagsangeboten.
 * 
 * Generated by: Claude AI via Bedrock
 * Target: Lokale Restaurants, Cafés, Bars mit digital-affiner Kundschaft
 * Personas: Anna (Gen Z/Yoga/Instagram/Bio), Markus (Familienvater/organisiert/Google/lokal)
 */

import { GoalRecommendation } from '../../types/goal-recommendations';

export const lunch_conversion_recommendations: GoalRecommendation[] = [
  {
    goalId: "lunch_conversion",
    recommendationId: "lunch_daily_gmb_posts",
    title: "Tägliche Google Posts mit Mittagsangeboten",
    description: "Poste jeden Morgen bis 10 Uhr dein aktuelles Mittagsmenü als Google My Business Post mit appetitlichen Fotos und Preisen. Nutze Call-to-Actions wie 'Jetzt reservieren' oder 'Heute verfügbar'. Diese Posts erscheinen prominent bei lokalen Suchanfragen und steigern die Mittagsbuchungen um durchschnittlich 40%.",
    platform: "Google",
    impactScore: 9,
    effortScore: 3,
    personaTargets: ["Bewahrer-Ben", "Solo-Sarah"]
  },
  {
    goalId: "lunch_conversion",
    recommendationId: "lunch_instagram_stories_countdown",
    title: "Instagram Stories mit Mittagsmenü-Countdown",
    description: "Erstelle täglich ansprechende Stories mit dem Mittagsmenü und nutze Countdown-Sticker für zeitlich begrenzte Angebote. Zeige die Zubereitung live oder präsentiere fertige Gerichte appetitlich. Dies schafft Dringlichkeit und motiviert spontane Mittagsbesuche, besonders bei digital-affinen Zielgruppen.",
    platform: "Instagram",
    impactScore: 8,
    effortScore: 4,
    personaTargets: ["Wachstums-Walter"]
  },
  {
    goalId: "lunch_conversion",
    recommendationId: "lunch_business_partnerships",
    title: "B2B-Partnerschaften mit nahegelegenen Büros",
    description: "Kontaktiere Unternehmen in der Nähe und biete spezielle Mittagsdeals für deren Mitarbeiter an. Erstelle Firmen-Lunch-Karten oder Catering-Optionen für Meetings. Biete Vorbestellung per WhatsApp oder App an, um Wartezeiten zu reduzieren. Dies generiert planbare, wiederkehrende Mittagsumsätze.",
    platform: "Offline",
    impactScore: 9,
    effortScore: 7,
    personaTargets: ["Ketten-Katrin", "Wachstums-Walter"]
  },
  {
    goalId: "lunch_conversion",
    recommendationId: "lunch_healthy_options_highlight",
    title: "Gesunde Mittagsoptionen prominent bewerben",
    description: "Entwickle und bewirb bewusst gesunde, leichte Mittagsgerichte wie Bowls, Salate oder vegane Optionen. Nutze Hashtags wie #healthylunch #officefood #quickbite auf Social Media. Dies spricht gesundheitsbewusste Berufstätige an und differenziert dich von Fast-Food-Konkurrenz.",
    platform: "Instagram",
    impactScore: 7,
    effortScore: 5,
    personaTargets: ["Wachstums-Walter"]
  },
  {
    goalId: "lunch_conversion",
    recommendationId: "lunch_express_service_promotion",
    title: "Express-Mittagsservice mit Zeitgarantie bewerben",
    description: "Führe einen 'Lunch in 15 Minuten'-Service ein und bewirb diesen aktiv auf Website, Google und Social Media. Erstelle spezielle Express-Gerichte und kommuniziere die Zeitgarantie klar. Dies löst das Hauptproblem vieler Berufstätiger (Zeitmangel) und positioniert dich als lunch-optimierte Location.",
    platform: "Website",
    impactScore: 8,
    effortScore: 6,
    personaTargets: ["Solo-Sarah", "Ketten-Katrin"]
  }
];

export default lunch_conversion_recommendations;