#!/usr/bin/env npx tsx

console.log('🔍 Debug: Starting...');

try {
  console.log('🔍 Debug: Importing validator...');
  const { KiroSystemPurityValidator } = await import('../src/lib/architecture-scanner/kiro-system-purity-validator');
  console.log('✅ Debug: Import successful');
  
  console.log('🔍 Debug: Creating validator instance...');
  const validator = new KiroSystemPurityValidator();
  console.log('✅ Debug: Validator created');
  
  console.log('🔍 Debug: Testing simple method...');
  const origin = (validator as any).detectOrigin('// Generated by Kiro\nexport const test = {}');
  console.log('✅ Debug: Origin detection result:', origin);
  
  console.log('🎉 Debug: All basic tests passed!');
} catch (error) {
  console.error('❌ Debug: Error occurred:', error);
  process.exit(1);
}