name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Supabase CLI
      run: |
        curl -L https://github.com/supabase/cli/releases/download/v2.31.8/supabase_2.31.8_linux_amd64.tar.gz \
          | tar xz supabase && sudo mv supabase /usr/local/bin/

    - name: Log into Supabase
      env:
        SUPABASE_TOKEN: ${{ secrets.SUPABASE_TOKEN }}
      run: supabase login --token $SUPABASE_TOKEN

    - name: Link to project
      run: supabase link --project-ref uheksobnyedarrpgxhju

    - name: Deploy enhanced-visibility-check
      run: supabase functions deploy enhanced-visibility-check

    - name: Deploy log_uploader
      run: supabase functions deploy log_uploader

    # ggf. weitere Functions hier