name: Green Core Validation
permissions:
  contents: read
  issues: write

on:
  pull_request:
    branches: [ main ]
    # Note: Add kiro-dev, aws-deploy when these branches are created
  push:
    branches: [ main ]

jobs:
  green-core:
    name: Green Core Tests (CI-Blocking)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run Green Core Tests
        run: npm run test:green-core
        env:
          CI: true
          NODE_ENV: test
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: green-core-test-results
          path: |
            coverage/
            test-results/
          retention-days: 7
          
      - name: Comment PR on failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚫 **Green Core Tests Failed**
              
              The critical system tests have failed. This PR cannot be merged until all Green Core tests pass.
              
              **Failed Tests:**
              - Kiro System Purity Validation
              - Persona Service Core Functions
              - TypeScript Compilation
              
              Please fix the failing tests and push your changes.
              
              **Target:** All tests must complete in <5 minutes with 99.9% reliability.`
            })
            
      - name: Block merge on failure
        if: failure()
        run: |
          echo "🚫 GREEN CORE TESTS FAILED - BLOCKING MERGE"
          echo "Critical system tests must pass before merging"
          exit 1

  extended-tests:
    name: Extended Test Suite (Non-Blocking)
    runs-on: ubuntu-latest
    needs: green-core
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run Extended Jest Tests
        run: npm run test:ci
        continue-on-error: true
        
      - name: Upload extended test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extended-test-results
          path: |
            coverage/
            test-results/
          retention-days: 30
          
      - name: Report extended test status
        if: always()
        run: |
          echo "📊 Extended test suite completed"
          echo "Results uploaded as artifacts for analysis"
