name: Green Core Validation

# minimal nötige Rechte für den GITHUB_TOKEN
permissions:
  contents: read

on:
  pull_request:
    branches: [ main, kiro-dev, aws-deploy ]
  push:
    branches: [ test/green-core-validation ]
  workflow_dispatch:

jobs:
  green-core:
    name: Green Core Tests (CI-Blocking)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: test/green-core-validation
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        env:
          CI: true
          
      # 🔎 Debug: Zeig mir exakt, was CI baut
      - name: Debug persona-api snippet
        run: sed -n '180,205p' src/services/persona-api.ts
        
      - name: Debug tests snippet
        run: sed -n '55,110p' src/services/__tests__/persona-api.basic.test.ts
        
      - name: Sanity - print commit + snippets
        run: |
          echo "Commit SHA: $(git rev-parse HEAD)"
          echo
          echo "---- Checks ----"
          (grep -n "toBeGreaterThanOrEqual(0\.7)" src/services/__tests__/persona-api.basic.test.ts && echo "OK: >= 0.7 vorhanden") || echo "FEHLT: >= 0.7"
          (grep -n "throw new Error" src/services/persona-api.ts && echo "UNEXPECTED: throw gefunden") || echo "OK: keine throws"
          
      - name: TypeScript Compilation
        run: npx tsc --noEmit --skipLibCheck
        
      - name: Kiro System Purity Validation
        run: npx jest --runInBand --passWithNoTests --testPathPattern="src/lib/architecture-scanner/__tests__/kiro-system-purity-validator.test.ts" --testNamePattern="should validate a pure Kiro system" --testPathIgnorePatterns="archive|infra|test/unit|test/smoke|architecture-compliance-checker"
        
      - name: Jest cache clear
        run: npx jest --clearCache
        
      - name: Persona Service Basic Tests
        run: npx jest --runTestsByPath src/services/__tests__/persona-api.basic.test.ts --testPathIgnorePatterns="__tests__/__wip__|__tests__/__failing__" --runInBand --maxWorkers=2 --verbose