name: Green Core Tests (CI-Blocking)
permissions:
  contents: read

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Green Core Tests (CI-Blocking)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: |
          if [ -f jest.config.cjs ]; then
            npx jest --config jest.config.cjs --passWithNoTests
          else
            npx jest --passWithNoTests
          fi

      - name: Lint validation
        run: |
          npx eslint . --max-warnings=1000 || echo "⚠️ ESLint warnings detected"

      - name: Report success
        run: echo "✅ Green Core Tests (CI-Blocking) completed successfully"
