name: Deploy Supabase CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Supabase CLI
        run: npm install -g supabase

      - name: Login to Supabase
        run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link to project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

      - name: Run database migrations
        run: supabase db push

      - name: Deploy Edge Functions
        run: supabase functions deploy --all
