name: Deploy Supabase CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Supabase CLI
        run: |
          # 1) Alte CLI-Reste entfernen
          rm -rf supabase supabase_linux_amd64.tar.gz

          # 2) Archiv herunterladen
          curl -L https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz \
            -o supabase_linux_amd64.tar.gz

          # 3) Archiv entpacken
          tar xzf supabase_linux_amd64.tar.gz

          # 4) Binary ausführbar machen und ins PATH verschieben
          chmod +x supabase
          sudo mv supabase /usr/local/bin

          # 5) Versionstest
          supabase version

      - name: Login to Supabase
        run: supabase login --token "${{ secrets.SUPABASE_ACCESS_TOKEN }}"

      - name: Link to project
        run: supabase link --project-ref "${{ secrets.SUPABASE_PROJECT_REF }}"

      - name: Run database migrations
        run: supabase db push

      - name: Deploy Edge Functions
        run: supabase functions deploy --all
