name: VC Pipeline

permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]
    paths:
      - "src/pages/vc/**"
      - "src/pages/VCResult.tsx"
      - "src/services/vc.ts"
      - "src/services/__tests__/vc.test.ts"
      - "scripts/vc_healthcheck.sh"
      - "package.json"
      - "README.md"

jobs:
  vc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
      - run: npm ci
      - run: npm run lint:vc
      - run: npm run build
      - run: npm run vc:healthcheck

  legacy-lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
      - run: npm ci
      - run: npm run lint || true
