name: Web Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  BUCKET: ${{ vars.BUCKET }}
  DIST_ID: ${{ vars.DIST_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build
        run: npm run build

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::055062860590:role/gh-actions-web-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload immutable assets
        run: aws s3 sync dist/assets s3://$BUCKET/assets --delete --cache-control "public,max-age=31536000,immutable"

      - name: Upload HTML (short cache)
        run: aws s3 cp dist/ s3://$BUCKET/ --recursive --exclude "*" --include "*.html" --cache-control "public,max-age=300" --content-type "text/html"

      - name: Upload manifest/robots/sitemap
        run: |
          aws s3 cp dist/site.webmanifest s3://$BUCKET/site.webmanifest --cache-control "public,max-age=86400" --content-type "application/manifest+json"
          aws s3 cp dist/robots.txt        s3://$BUCKET/robots.txt        --cache-control "public,max-age=300"   --content-type "text/plain"
          aws s3 cp dist/sitemap.xml       s3://$BUCKET/sitemap.xml       --cache-control "public,max-age=300"   --content-type "application/xml"

      - name: Upload rest (ohne assets & *.html)
        run: aws s3 sync dist/ s3://$BUCKET --delete --exclude "assets/*" --exclude "*.html"

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths "/" "/index.html" "/site.webmanifest" "/favicons/*" "/favicon.ico" "/robots.txt" "/sitemap.xml"
